"use client";

import jsPDF from "jspdf";
import type { FormExtractionResult } from "@/app/types";
import { getFormName } from "@/app/lib/acord-fields";

const LINE = 8;

export function generatePdf(result: FormExtractionResult): void {
  const doc = new jsPDF();
  const { formType, fields, fillRate, totalFields, filledFields, flaggedFields } = result;
  let y = 20;

  // header — form name + generation timestamp
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(getFormName(formType), 14, y); y += LINE;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated by Bindery AI · ${new Date().toLocaleDateString()}`, 14, y); y += LINE * 1.5;

  doc.setDrawColor(200);
  doc.line(14, y, 196, y); y += LINE;

  // one row per field — color-coded by status
  doc.setFontSize(10);
  fields.forEach((field) => {
    // overflow onto a new page if near the bottom
    if (y > 270) { doc.addPage(); y = 20; }

    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text(field.fieldName, 14, y);

    doc.setFont("helvetica", "normal");
    if (field.flagged) {
      doc.setTextColor(180, 100, 0);           // amber — needs review
      doc.text(`[FLAGGED] ${field.value}`, 90, y);
    } else if (!field.value) {
      doc.setTextColor(180, 0, 0);             // red — missing
      doc.text("MISSING", 90, y);
    } else {
      doc.setTextColor(0);                     // black — filled
      doc.text(field.value, 90, y);
    }

    y += LINE;
  });

  // fill-rate footer
  y += 4;
  doc.setDrawColor(200);
  doc.line(14, y, 196, y); y += LINE;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80);
  doc.text(
    `Fill Rate: ${filledFields}/${totalFields} fields (${fillRate}%)  ·  ${flaggedFields} flagged for review`,
    14, y
  );

  doc.save(`${formType.replace(" ", "_")}_bindery.pdf`);
}
