"use client";

import jsPDF from "jspdf";
import type { FormExtractionResult } from "@/app/types";
import { getFormName } from "@/app/lib/acord-fields";

const LINE = 8;

export function generatePdf(result: FormExtractionResult): void {
  const doc = new jsPDF();
  const { formType, fields } = result;
  let y = 20;

  // header — form name + generation timestamp
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0);
  doc.text(getFormName(formType), 14, y); y += LINE;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`Generated by Bindery AI · ${new Date().toLocaleDateString()}`, 14, y); y += LINE * 1.5;

  doc.setDrawColor(200);
  doc.line(14, y, 196, y); y += LINE;

  // one row per field — color-coded by status, long values wrap to fit right margin
  const VALUE_X = 90;
  const MAX_WIDTH = 196 - VALUE_X;  // right margin at 196, value column starts at 90
  doc.setFontSize(10);

  fields.forEach((field) => {
    const displayValue = field.flagged ? `[FLAGGED] ${field.value}` : field.value || "MISSING";
    // wrap text to max width so nothing overflows the right margin
    const wrapped = doc.splitTextToSize(displayValue, MAX_WIDTH);
    const rowHeight = wrapped.length * LINE;

    // overflow onto a new page if this row won't fit
    if (y + rowHeight > 270) { doc.addPage(); y = 20; }

    doc.setFont("helvetica", "bold");
    doc.setTextColor(0);
    doc.text(field.fieldName, 14, y);

    doc.setFont("helvetica", "normal");
    if (field.flagged)   doc.setTextColor(180, 100, 0);  // amber — needs review
    else if (!field.value) doc.setTextColor(180, 0, 0);  // red — missing
    else                 doc.setTextColor(0);             // black — filled

    doc.text(wrapped, VALUE_X, y);
    y += rowHeight;
  });

  // closing divider
  y += 4;
  doc.setDrawColor(200);
  doc.line(14, y, 196, y);

  doc.save(`${formType.replace(" ", "_")}_bindery.pdf`);
}
